// Generated by tools/pgs-achievements.py from store/play-games/achievements.json
// and the ids the Play Console replied with. Do not edit by hand: run the tool.

namespace Wildgrove.Game.Services
{
    /// <summary>
    /// Play Games Services achievement IDs — the encoded console ids, not the
    /// resource names. Every constant here must be evaluated by
    /// <see cref="Achievements"/>; a test fails if one is not.
    /// </summary>
    public static class AchievementIds
    {
        /// <summary>"First Harvest" — Bring your first load of gathered goods home to camp.</summary>
        public const string FirstHarvest = "CggIp4me7kEQAhA5";

        /// <summary>"First Friends" — Befriend three familiars so the trails are not walked alone.</summary>
        public const string FirstFriends = "CggIp4me7kEQAhAy";

        /// <summary>"Off the Beaten Path" — Map a trail to a second zone and open it.</summary>
        public const string OffTheBeatenPath = "CggIp4me7kEQAhBD";

        /// <summary>"Fire and Fruit" — Finish a first batch of goods at a camp station.</summary>
        public const string FireAndFruit = "CggIp4me7kEQAhA-";

        /// <summary>"Green Hands" — Replant a node's own resource and raise its richness.</summary>
        public const string GreenHands = "CggIp4me7kEQAhBE";

        /// <summary>"A Full Basket" — Gather a thousand units of the grove's goods.</summary>
        public const string AFullBasket = "CggIp4me7kEQAhBV";

        /// <summary>"The Long Haul" — Gather a hundred thousand units.</summary>
        public const string TheLongHaul = "CggIp4me7kEQAhBY";

        /// <summary>"Laden Trails" — Gather ten million units.</summary>
        public const string LadenTrails = "CggIp4me7kEQAhBW";

        /// <summary>"The Grove Gives" — Gather a thousand million units.</summary>
        public const string TheGroveGives = "CggIp4me7kEQAhAz";

        /// <summary>"The Whole Camp Working" — Finish a batch at every station in the camp.</summary>
        public const string TheWholeCampWorking = "CggIp4me7kEQAhBZ";

        /// <summary>"Steady Hands" — Craft ten thousand goods.</summary>
        public const string SteadyHands = "CggIp4me7kEQAhBa";

        /// <summary>"Stores Overflowing" — Craft a million goods.</summary>
        public const string StoresOverflowing = "CggIp4me7kEQAhBI";

        /// <summary>"First kith" — Get your first bonded familiar!</summary>
        public const string FirstKith = "CggIp4me7kEQAhAC";

        /// <summary>"A Second Bond" — Earn both of the grove's bonded familiars.</summary>
        public const string ASecondBond = "CggIp4me7kEQAhBR";

        /// <summary>"Six at Post" — Hold six of the kith at their posts at once.</summary>
        public const string SixAtPost = "CggIp4me7kEQAhBT";

        /// <summary>"Well Known" — Raise a familiar to the fifth level of Kinship.</summary>
        public const string WellKnown = "CggIp4me7kEQAhBP";

        /// <summary>"Inseparable" — Carry one familiar past every milestone of Kinship.</summary>
        public const string Inseparable = "CggIp4me7kEQAhA4";

        /// <summary>"The Whole Wood" — Befriend every species that walks the grove.</summary>
        public const string TheWholeWood = "CggIp4me7kEQAhBB";

        /// <summary>"Pristine" — Find your first Pristine specimen.</summary>
        public const string Pristine = "CggIp4me7kEQAhBG";

        /// <summary>"Fixed in Ink" — Fix a Pristine specimen into the Folio.</summary>
        public const string FixedInInk = "CggIp4me7kEQAhAx";

        /// <summary>"A Spread Complete" — Fill every entry of one Folio spread.</summary>
        public const string ASpreadComplete = "CggIp4me7kEQAhBA";

        /// <summary>"Half the Folio" — Complete five of the Folio's spreads.</summary>
        public const string HalfTheFolio = "CggIp4me7kEQAhA6";

        /// <summary>"The Whole Folio" — Complete every spread in the Folio.</summary>
        public const string TheWholeFolio = "CggIp4me7kEQAhA2";

        /// <summary>"The Full Cabinet" — Fix a specimen of every resource the grove yields.</summary>
        public const string TheFullCabinet = "CggIp4me7kEQAhBL";

        /// <summary>"First Sketch" — Draw a first line at an observation site.</summary>
        public const string FirstSketch = "CggIp4me7kEQAhA0";

        /// <summary>"A Plate Recorded" — Finish an insect plate and record it.</summary>
        public const string APlateRecorded = "CggIp4me7kEQAhAw";

        /// <summary>"Every Plate Drawn" — Record a plate for every insect of the grove.</summary>
        public const string AllFivePlates = "CggIp4me7kEQAhBN";

        /// <summary>"Something Older" — Surface a first piece of deep amber.</summary>
        public const string SomethingOlder = "CggIp4me7kEQAhBM";

        /// <summary>"The Deep Pages" — Surface every piece of deep amber the grove is keeping.</summary>
        public const string TheDeepPages = "CggIp4me7kEQAhA9";

        /// <summary>"First Verse" — Complete a verse of the Rite.</summary>
        public const string FirstVerse = "CggIp4me7kEQAhBH";

        /// <summary>"The Rite Complete" — Complete every revealed verse of a Rite.</summary>
        public const string TheRiteComplete = "CggIp4me7kEQAhA1";

        /// <summary>"Five Verses Sung" — Sing five verses across all your runs.</summary>
        public const string FiveVerses = "CggIp4me7kEQAhBF";

        /// <summary>"Twenty-Five Verses Sung" — Sing twenty-five verses across all your runs.</summary>
        public const string TwentyFiveVerses = "CggIp4me7kEQAhA7";

        /// <summary>"The First Fold" — Fold the camp and follow the migration.</summary>
        public const string TheFirstFold = "CggIp4me7kEQAhBX";

        /// <summary>"Three Folds" — Follow the migration three times.</summary>
        public const string ThreeFolds = "CggIp4me7kEQAhBb";

        /// <summary>"Ten Folds" — Follow the migration ten times.</summary>
        public const string TenFolds = "CggIp4me7kEQAhBK";

        /// <summary>"Verdant" — Hold a thousand Verdure at once.</summary>
        public const string Verdant = "CggIp4me7kEQAhBC";

        /// <summary>"Reader of Stones" — Read the inscriptions on four waystones.</summary>
        public const string ReaderOfStones = "CggIp4me7kEQAhBS";

        /// <summary>"Every Stone Read" — Read the inscription on every waystone in the grove.</summary>
        public const string EveryStoneRead = "CggIp4me7kEQAhA3";

        /// <summary>"Into the Hollows" — Walk the trail down into The Hollows.</summary>
        public const string IntoTheHollows = "CggIp4me7kEQAhBU";

        /// <summary>"Cloudreach" — Stand on the Cloudreach Peaks: the last ground the grove has.</summary>
        public const string Cloudreach = "CggIp4me7kEQAhBO";

        /// <summary>"Steel in Hand" — Carry a full steel toolset.</summary>
        public const string SteelInHand = "CggIp4me7kEQAhA8";

        /// <summary>"The Almanac Opens" — Buy five nodes of the Almanac.</summary>
        public const string TheAlmanacOpens = "CggIp4me7kEQAhBQ";

        /// <summary>"The Almanac Complete" — Buy every node the Almanac holds.</summary>
        public const string TheAlmanacComplete = "CggIp4me7kEQAhBJ";

        /// <summary>"A Fuller Grove" — Raise all five lines of the camp past their debut.</summary>
        public const string AFullerGrove = "CggIp4me7kEQAhA_";

        /// <summary>Every achievement this build knows about.</summary>
        public static readonly string[] All =
        {
            FirstHarvest,
            FirstFriends,
            OffTheBeatenPath,
            FireAndFruit,
            GreenHands,
            AFullBasket,
            TheLongHaul,
            LadenTrails,
            TheGroveGives,
            TheWholeCampWorking,
            SteadyHands,
            StoresOverflowing,
            FirstKith,
            ASecondBond,
            SixAtPost,
            WellKnown,
            Inseparable,
            TheWholeWood,
            Pristine,
            FixedInInk,
            ASpreadComplete,
            HalfTheFolio,
            TheWholeFolio,
            TheFullCabinet,
            FirstSketch,
            APlateRecorded,
            AllFivePlates,
            SomethingOlder,
            TheDeepPages,
            FirstVerse,
            TheRiteComplete,
            FiveVerses,
            TwentyFiveVerses,
            TheFirstFold,
            ThreeFolds,
            TenFolds,
            Verdant,
            ReaderOfStones,
            EveryStoneRead,
            IntoTheHollows,
            Cloudreach,
            SteelInHand,
            TheAlmanacOpens,
            TheAlmanacComplete,
            AFullerGrove,
        };
    }
}
