using System.IO;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEngine;

namespace Wildgrove.EditorTools
{
    /// <summary>
    /// Refuses an Android build whose Firebase maven repo is missing or is not
    /// the version <c>Packages/manifest.json</c> pins.
    /// <para>
    /// <c>Assets/GeneratedLocalRepo/Firebase</c> is generated by
    /// <c>tools/fetch-google-packages.sh</c> and is not committed, so a clone
    /// that has not run the script has no Firebase to resolve — and the way
    /// Gradle says so is a wall of unresolved-dependency text a long way from
    /// the cause. Worse is the quiet case: bump the version in the script and
    /// the manifest, skip the re-run, and Gradle finds the OLD artifacts still
    /// sitting in the repo and links them while every file in the project says
    /// otherwise. The manifest is the pin this checks against, because it is
    /// the one both halves have to agree with.
    /// </para>
    /// <para>
    /// The .meta check is not belt-and-braces. An .aar under Assets/ with no
    /// .meta is imported by Unity as an ordinary Android plugin, so the library
    /// lands in the build a second time and Gradle fails on duplicate classes;
    /// the generated .meta disables it on every platform and carries EDM4U's
    /// "gpsr" label, which a .meta Unity wrote for itself never does.
    /// </para>
    /// </summary>
    public sealed class FirebaseRepoGuard : IPreprocessBuildWithReport
    {
        private static readonly string[] Products = { "analytics", "app", "crashlytics" };

        private const string RepoRoot = "Assets/GeneratedLocalRepo/Firebase/m2repository/com/google/firebase";
        private const string ManifestPath = "Packages/manifest.json";
        private const string FetchScript = "tools/fetch-google-packages.sh";

        public int callbackOrder => 0;

        public void OnPreprocessBuild(BuildReport report)
        {
            if (report.summary.platform != BuildTarget.Android)
            {
                return;
            }

            var version = PinnedVersion();
            if (string.IsNullOrEmpty(version))
            {
                throw new BuildFailedException(
                    ManifestPath + " does not pin com.google.firebase.app to a file: tarball — "
                    + "the Firebase version cannot be read, so the build cannot be checked against it.");
            }

            foreach (var product in Products)
            {
                var artifact = "firebase-" + product + "-unity-" + version;
                var aar = RepoRoot + "/firebase-" + product + "-unity/" + version + "/" + artifact + ".aar";

                if (!File.Exists(aar))
                {
                    throw new BuildFailedException(
                        "Firebase " + version + " is pinned in " + ManifestPath + " but " + aar
                        + " is not there. Run " + FetchScript + " and build again.");
                }

                if (!File.Exists(aar + ".meta") || !File.ReadAllText(aar + ".meta").Contains("gpsr"))
                {
                    throw new BuildFailedException(
                        aar + " has no generated .meta, so Unity will import it as a plugin as well as "
                        + "Gradle resolving it, and the build will fail on duplicate classes. Run "
                        + FetchScript + " and build again.");
                }
            }

            Debug.Log("[firebase] resolving against the generated repo, Firebase " + version + ".");
        }

        /// <summary>The Firebase version the manifest pins, or null when it pins none.</summary>
        private static string PinnedVersion()
        {
            if (!File.Exists(ManifestPath))
            {
                return null;
            }

            // The manifest is the only place the version is written down that
            // both Unity and the fetch script already read, so it is the pin
            // rather than a constant here that could drift from either.
            var match = Regex.Match(File.ReadAllText(ManifestPath),
                @"""com\.google\.firebase\.app""\s*:\s*""file:GooglePackages/com\.google\.firebase\.app-([0-9][0-9.]*)\.tgz""");
            return match.Success ? match.Groups[1].Value : null;
        }
    }
}
